### ISSUE TITLE
Starter dependent on spring-boot-data-jpa

### ISSUE THREAD

**Issue by robert-bor** [42BV/beanmapper-spring-boot-starter#1]

**Comment by hammersyko** [comment]
Had the same issue. Problem was with org.springframework.data.repository.core.EntityInformation usage in BeanMapperAutoConfig.

Only adding the Spring Data Core dependency (instead of the whole spring-boot-starter) did not fix the issue.

"Workaround" was to remove the beanmapper-spring-boot-starter dependency and provide the configuration myself; so regular flow without this dependency.
